FROM node:10-alpine
WORKDIR /var/app/current
RUN ls /var/app/current
COPY client/package*.json ./
RUN ls /var/app/current
COPY client/package.json /var/app/current/
RUN npm install
COPY client/ ./

RUN ls /var/app/current

COPY entrypoint.client.sh /var/app/current/
CMD ["/bin/sh", "/var/app/current/entrypoint.client.sh"]