FROM quay.io/eformat/curriki-api-base:latest

EXPOSE 8000

COPY api-init-container.sh /usr/local/bin/
COPY api-entrypoint.sh /usr/local/bin/
COPY api-laravel-echo-server.sh /usr/local/bin/
COPY api-queue-worker.sh /usr/local/bin/

CMD [ "/bin/sh", "-c", "/usr/local/bin/api-entrypoint.sh" ]