pipeline {
  agent {
    label "master"
  }

  environment {

  }

  options {
      buildDiscarder(logRotator(numToKeepStr: '50', artifactNumToKeepStr: '1'))
      timeout(time: 15, unit: 'MINUTES')
      ansiColor('xterm')
      timestamps()
  }

  stages {
    stage('Test') {

    }
}